/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Mary
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu = new javax.swing.JMenu();
        JMenuItemClientes = new javax.swing.JMenuItem();
        JMenuItemFuncionarios = new javax.swing.JMenuItem();
        JMenuItemFornecedores = new javax.swing.JMenuItem();
        JMenuItemVendas = new javax.swing.JMenuItem();
        JMenuItemProdutos = new javax.swing.JMenuItem();
        JMenuRelatorio = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Lahmendz Store");
        setEnabled(false);
        getContentPane().setLayout(null);

        jMenu.setText("Menu");

        JMenuItemClientes.setText("Clientes");
        jMenu.add(JMenuItemClientes);

        JMenuItemFuncionarios.setText("Funcionários");
        jMenu.add(JMenuItemFuncionarios);

        JMenuItemFornecedores.setText("Fornecedores");
        JMenuItemFornecedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMenuItemFornecedoresActionPerformed(evt);
            }
        });
        jMenu.add(JMenuItemFornecedores);

        JMenuItemVendas.setText("Vendas");
        jMenu.add(JMenuItemVendas);

        JMenuItemProdutos.setText("Produtos");
        JMenuItemProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMenuItemProdutosActionPerformed(evt);
            }
        });
        jMenu.add(JMenuItemProdutos);

        jMenuBar1.add(jMenu);

        JMenuRelatorio.setText("Relatório");
        jMenuBar1.add(JMenuRelatorio);

        setJMenuBar(jMenuBar1);

        getAccessibleContext().setAccessibleDescription("");

        setBounds(0, 0, 617, 460);
    }// </editor-fold>//GEN-END:initComponents

    private void JMenuItemFornecedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMenuItemFornecedoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JMenuItemFornecedoresActionPerformed

    private void JMenuItemProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMenuItemProdutosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JMenuItemProdutosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem JMenuItemClientes;
    private javax.swing.JMenuItem JMenuItemFornecedores;
    private javax.swing.JMenuItem JMenuItemFuncionarios;
    private javax.swing.JMenuItem JMenuItemProdutos;
    private javax.swing.JMenuItem JMenuItemVendas;
    private javax.swing.JMenu JMenuRelatorio;
    private javax.swing.JMenu jMenu;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
